### ISSUE TITLE
Update for Final Draft

### ISSUE THREAD

**Issue by keilw** [JavaMoney/JavaMoney.github.io#10]

**Comment by atsticks** [comment]
just for info:

I am currently also preparing the Java 6/7 backport. API is already done,
RI should be another hour or two of work ;)

Cheers,
Anatole


2015-03-11 20:39 GMT+01:00 Werner Keil <notifications@github.com>:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/JavaMoney.github.io/issues/10>.
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
Please see the issues, could you rename the RI accordingly, either "javamoney-impl-bp" (to match the API one) or "moneta-bp" (since Monate is the "Implementation" project but not as sensitive as the unique term "RI") "jsr354" should certainly not be in any of the BP projects, also see how 310 did that (this was done properly, I also pointed it out in the EC to avoid confusions with the actual JSR ;-) )

**Comment by keilw** [comment]
Done
