### ISSUE TITLE
Check in JBake source for this web site.

### ISSUE THREAD

**Issue by msgilligan** [JavaMoney/JavaMoney.github.io#15]
The JBake source for this site should be checked in somewhere. Since this is the repository for an Organization page, the `master` branch should contain the rendered page. The source code should either be in a `source` branch or perhaps a separate repository.

**Comment by keilw** [comment]
It is in a separate repository: https://github.com/JavaMoney/JavaMoney-template-bootstrap

**Comment by msgilligan** [comment]
Thanks! I updated PR #14 with this information and a link.
