### ISSUE TITLE
Publish javax.money javadoc on website

### ISSUE THREAD

**Issue by gsmet** [JavaMoney/JavaMoney.github.io#27]
Hi!

We had javax.money validators contributed recently to Hibernate Validators and we wanted to point to the javax.money Javadoc in our Javadoc. I haven't found any good place to point out our links (the only published Javadoc I found is on javadox with a lot of ads). Could you envision to publish the Javadoc on the javamoney.github.io website at a stable URL?

Thanks!
## 

Guillaume

**Comment by keilw** [comment]
Doing so with Maven often runs into bugs or problems on the GitHub side (the build fails with some dubious "abuse warning" but manually it should be possible. See http://unitsofmeasurement.github.io/unit-api/site/apidocs/index.html

**Comment by gsmet** [comment]
Yes, I don't think it changes that much and it would be nice to have the Javadoc online on the reference site.

Thanks!

**Comment by keilw** [comment]
As the Maven site goal has problems, but regular build of the API creates an "apidocs" folder, simily used that.

**Comment by keilw** [comment]
It can be found under [http://javamoney.github.io/apidocs/](apidocs)

**Comment by gsmet** [comment]
Thanks Werner! Greatly appreciated!
