### ISSUE TITLE
HTTPS for javamoney.org

### ISSUE THREAD

**Issue by stokito** [JavaMoney/JavaMoney.github.io#35]
Now http://javamoney.org/ makes redirect to  http://javamoney.github.io/ i.e. it uses HTTP instead of HTTPS. It can make a redirect to https://javamoney.github.io/ instead.
But https://javamoney.org/ doesn't work at all.
Even when you making a search in Google it shows http://javamoney.github.io/ instead of javamoney.org.

Please make javamoney.org working on HTTPS and without redirect to github.io as described here
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by keilw** [comment]
Will have to check with the domain registrar. Https://javamoney.org likely won't work I'm afraid, but we are not providing APIs from the site, so it seems uncritical. Unfortunately the registrar does not support CNAME and with their A Records it also never worked.
